---
- name: Create devops user
  user:
    name: devops
    shell: /bin/bash

- name: Allow devops user passwordless sudo for any command
  copy:
    dest: /etc/sudoers.d/devops
    mode: 0400
    content: |
        devops ALL=(ALL) NOPASSWD: ALL
    validate: 'visudo -scf %s'
